echo "// Autogenerated by concantenating several files: " > smart-api-client.js
echo "// DO NOT EDIT. " >> smart-api-client.js
echo "// cat ../../jquery/jquery.js jquery-ui.js  jquery.rdfquery.core-1.0.js jschannel.js smart-api-client-base.js  > smart-api-client.js"  >> smart-api-client.js
cat ../../jquery/jquery.js jquery-ui.js  jquery.rdfquery.core-1.0.js jschannel.js smart-api-client-base.js  >> smart-api-client.js